### PR TITLE
Natural newline

### PR DESCRIPTION
**Pull request by uga-rosa**
#5

### CODE REVIEW

**Comment by uga-rosa** [comment]
@askfiy Try it. English to Chinese translation should work.

**Comment by uga-rosa** [comment]
If you don't mind, please help me add Chinese to the rules of `parse_before/natural`.

**Comment by askfiy** [comment]
Okay, let me try it, is it only for English to Chinese translations?

**Comment by uga-rosa** [comment]
I don't know Chinese grammar, so I can't judge sentence endings.
In Chinese, when which character comes, does it mean that the sentence is over? (In English, it would be `.`, `!`, or `?`)

**Comment by askfiy** [comment]
. -> 。
! -> ！
? -> ？
: -> ：

**Comment by uga-rosa** [comment]
Thanks. I added it. Please check it out.

**Comment by askfiy** [comment]
I tried the English to Chinese translation and it was very good.

**Comment by askfiy** [comment]
The input from Chinese to English is generally no problem, but some details are still confusing.

for example:

图片

**Comment by uga-rosa** [comment]
Hmmm. It works well in Japanese.
image
Is this the default setting?

**Comment by uga-rosa** [comment]
Can you post that text so I can copy it?

**Comment by askfiy** [comment]
I'm using the default settings, should I specify sorce as ZH? Now I didn't specify.

测试选项：

- 1. 这是条目1。
- 2. 这是条目2！
- 3. 这是条目3？

**Comment by uga-rosa** [comment]
Ah, yes. There's no automatic detection of the original language.

**Comment by uga-rosa** [comment]
If I pass the source option, it works properly.

**Comment by askfiy** [comment]
I don't know how to set him up now, can you help me?

The result is always incorrect, it gets Chinese now, even if I press the leader tse.

I am using the default settings.

```
        translator = {
            {"n", "<leader>tsc", ":<c-u>Translate ZH -source=EN -output=split<cr>", "ntst"},
            {"x", "<leader>tsc", ":Translate ZH -source=EN -output=split<cr>", "ntst"},

            {"n", "<leader>tse", ":<c-u>Translate EN -source=ZH -output=split<cr>", "ntst"},
            {"x", "<leader>tse", ":Translate EN -source=ZN -output=split<cr>", "ntst"},

            {"n", "<leader>trc", ":<c-u>Translate ZH -source=EN -output=replace<cr>", "ntst"},
            {"x", "<leader>trc", ":Translate ZH -source=EN -output=replace<cr>", "ntst"},

            {"n", "<leader>tre", ":<c-u>Translate EN -source=ZH -output=replace<cr>", "ntst"},
            {"x", "<leader>tre", ":Translate EN -source=ZH -output=replace<cr>", "ntst"}
        }
```

**Comment by uga-rosa** [comment]
typo

**Comment by askfiy** [comment]
It works fine now, I'm such a careless person. You are amazing dear.

**Comment by uga-rosa** [comment]
Ok. Thank you for your cooperation.

**Comment by askfiy** [comment]
I have an idea, is it possible to not check the end symbol?

Instead, let's insert a placeholder at the end before translating, and then wrap the line according to this placeholder?

This will wrap the line correctly even without the end of a specific symbol.

**Comment by askfiy** [comment]
e.g. <!@@!>

**Comment by uga-rosa** [comment]
If I force myself to translate all the lines separately, the results of translating long sentences that span multiple lines will be incorrect. I want to avoid that.

**Comment by uga-rosa** [comment]
So we need to distinguish where we should bond and where we should not.

**Comment by askfiy** [comment]
A complete sentence should not span multiple lines.

In markdown, a sentence that spans lines is considered a paragraph.

Splitting based on placeholders has 2 benefits:

1. One can get line breaks without having to obey a specific symbol
2. You also don't have to match symbols for each language between it and other languages

Anyway, it's great now.

This is just a suggestion, in order to lighten your workload I think you can consider it.

**Comment by askfiy** [comment]
OK, so go ahead as you want. It's also good to use a trailing symbol to determine if a newline should be used. It can make people's writing behavior more standardized.

**Comment by askfiy** [comment]
I tested the performance of wrapping lines with trailing symbols.

The following is a translation of the documentation for Python's built-in socketserver, which is still not very easy to read.

图片

This is Japanese:

图片

Let's take a look at vscode comment translate：

图片

**Comment by uga-rosa** [comment]
How about adding a colon to the end-of-sentence rule and a sentence-initial rule (e.g., in English, if the beginning of a line is capitalized, that is the start of the sentence)?

**Comment by askfiy** [comment]
> How about adding a colon to the end-of-sentence rule and a sentence-initial rule (e.g., in English, if the beginning of a line is capitalized, that is the start of the sentence)?

Do it when you come back from your trip, it's very late in Japan now and you need to rest.

**Comment by askfiy** [comment]
So far it looks normal, but not indented

I tried it with some translation documents and each line is correctly distinguished

I didn't do anything

```

*********** translate/config.lua ***********

    parse_befor = {
        ...
        no_handle = require("translate.preset.parse_before.no_handle")
    }

    parse_after = {
        ...

        no_handle = require("translate.preset.parse_after.no_handle")
    }

    default = {
        parse_before = "no_handle",
        command = "translate_shell",
        parse_after = "no_handle",
        output = "floating"
    },

************ parse_befor/no_handle.lua ***********

local M = {}

function M.cmd(lines, _)
    return lines
end

return M


************ parse_after/no_handle.lua ***********

M = {}

M.cmd = function(lines, _)
    return lines
end

return M

```

**Comment by uga-rosa** [comment]
The deepl translation erases line breaks. So it will not work without this method.

**Comment by askfiy** [comment]
I'm using translate-shell and it's perfect.

**Comment by uga-rosa** [comment]
Some things are automatically added to parse_after. I wonder if that mechanism worked well.

**Comment by uga-rosa** [comment]
And it's a recent change to allow selections to be passed on as a list. Originally, they were combined into a single string.

**Comment by askfiy** [comment]
It's perfect, except the indentation is not normal.

If we fixed the indentation, it would be really cool, you can look at this picture, everything works fine except for the indentation.

I haven't tested the translation of the word, so please wait.

图片

**Comment by uga-rosa** [comment]
Well, if it works, good for you. no_handle should be added later.
The indentation calculation was only handled as a work in progress, so I'll make sure it's done right. Separation of functions is difficult...

**Comment by askfiy** [comment]
It's in Japanese, I'm not sure if it's correct, you can take a look.

图片

图片

We can notice that the number of spaces in the middle of this block diagram seems to be wrong.

I don't know if this is caused by the indentation error.

图片

But vscode comment translate still works well. I'm also very curious how it does it.

It's still indented wrong, but it doesn't affect reading.

图片

**Comment by askfiy** [comment]
Do you know a plugin called Translator for the KDE desktop? It also uses translate-shell internally.

I noticed that its translation of the diagram is the same as the plugin's translation, the spaces between the lines are removed.

It's not a big problem, it doesn't affect reading very much, and I rarely translate the whole picture at work.

But Translator preserves the previous indentation. I think that's fine, what do you think?


图片

图片

**Comment by askfiy** [comment]
Let's forget about the space between lines, it's probably only valid for structure diagrams.

But there are very few translation scenarios for structure diagrams.

The indentation at the beginning of each line should be consistent.

The advantage of no_handle is that it aligns the English and the translated result as much as possible. 

Obviously they are aligned。

Now the results are translated into Japanese and then into English, and the reading is still very smooth.



图片

图片

**Comment by askfiy** [comment]
Floats should show more content in less space.

I myself would translate the float to one line instead of multiple lines.

It is necessary to keep the indentation of the split, because the split can be very intuitive to compare the original text.

This is my opinion.

**Comment by askfiy** [comment]
Well, I'm not sure if it's available in deepl.

I overlooked a bug, which may require you to try it yourself if it helps.

What I can say for sure is that it works perfectly in translate_shell.

**Comment by uga-rosa** [comment]
I have stopped calculating indentation. Instead, parse_before/trim now updates the selection so that whitespace before and after is maintained.

**Comment by askfiy** [comment]
It's perfect now, can you add a wiki page?

I want to describe this plugin for more Chinese who use it.

**Comment by uga-rosa** [comment]
https://github.com/uga-rosa/translate.nvim/wiki
Can't you edit it from here?

**Comment by askfiy** [comment]
it's OK now

**Comment by askfiy** [comment]
When I try to use the default configuration it tells me an error:

```
require("translate").setup()
```

```
Error detected while processing /home/askfiy/.config/nvim/lua/configure/plugins/translate.lua:
E5113: Error while calling lua chunk: vim/shared.lua:260: after the second argument: expected table, got nil
stack traceback:
        [C]: in function 'error'
        vim/shared.lua:608: in function 'validate'
        vim/shared.lua:260: in function 'tbl_deep_extend'
        .../pack/packer/opt/translate.nvim/lua/translate/config.lua:100: in function 'setup'
        lua/configure/plugins/translate.lua:29: in main chunk
```

Maybe you should check.

**Comment by uga-rosa** [comment]
Oh, didn't I write that? Without arguments, you'll get an error.
The setup function of this plugin only rewrites the settings each time it is called, so there is no need to call setup if you use the default settings.
Also, if you have a problem, please make an individual issue. It's hard to manage.

**Comment by askfiy** [comment]
ok i got it, thank you very much

**Pull request merged**
